### ISSUE TITLE
Do not restart adapter system.adapter.eventlist.0 because restart loop detected

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.eventlist#23]
Habe grade mal den Event-Adpter installiert. Startet erst und dann loopt er:
 
js-controller:3.3.17
node.js: 12.22.6
NPM:6.14.15
Version: 0.4.4 & 0.4.2

Folgende Fehlermeldung taucht im Debug-Log auf:
`2021-09-10 17:04:31.884 - error: eventlist.0 (20201) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-09-10 17:04:31.884 - error: eventlist.0 (20201) unhandled promise rejection: Cannot read property 'replace' of undefined
2021-09-10 17:04:31.885 - error: eventlist.0 (20201) TypeError: Cannot read property 'replace' of undefined
at formatEvent (/opt/iobroker/node_modules/iobroker.eventlist/main.js:355:47)
at /opt/iobroker/node_modules/iobroker.eventlist/main.js:686:24
at new Promise ()
at /opt/iobroker/node_modules/iobroker.eventlist/main.js:621:21
2021-09-10 17:04:31.885 - error: eventlist.0 (20201) Cannot read property 'replace' of undefined
2021-09-10 17:04:31.888 - info: eventlist.0 (20201) terminating
2021-09-10 17:04:31.888 - warn: eventlist.0 (20201) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-09-10 17:04:32.453 - error: host.iobroker instance system.adapter.eventlist.0 terminated with code 6 (UNCAUGHT_EXCEPTION)`

**Comment by DocGame69** [comment]
Hier seit ewigen Zeiten das selbe Problem. Sind wir wirklich die einzigen, da keine Antwort kommt?
`<html><body>


host.iobroker | 2021-12-01 18:39:06.903 | info | Restart adapter system.adapter.eventlist.0 because enabled
-- | -- | -- | --
host.iobroker | 2021-12-01 18:39:06.902 | error | instance system.adapter.eventlist.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
eventlist.0 | 2021-12-01 18:39:06.299 | warn | (27217) Terminated (UNCAUGHT_EXCEPTION): Without reason
eventlist.0 | 2021-12-01 18:39:06.299 | info | (27217) terminating
eventlist.0 | 2021-12-01 18:39:06.289 | error | (27217) Cannot read property 'replace' of undefined
eventlist.0 | 2021-12-01 18:39:06.289 | error | at /opt/iobroker/node_modules/iobroker.eventlist/main.js:621:21
eventlist.0 | 2021-12-01 18:39:06.289 | error | at new Promise (<anonymous>)
eventlist.0 | 2021-12-01 18:39:06.289 | error | at /opt/iobroker/node_modules/iobroker.eventlist/main.js:686:24
eventlist.0 | 2021-12-01 18:39:06.289 | error | at formatEvent (/opt/iobroker/node_modules/iobroker.eventlist/main.js:355:47)
eventlist.0 | 2021-12-01 18:39:06.289 | error | (27217) TypeError: Cannot read property 'replace' of undefined
eventlist.0 | 2021-12-01 18:39:06.289 | error | (27217) unhandled promise rejection: Cannot read property 'replace' of undefined
eventlist.0 | 2021-12-01 18:39:06.289 | error | (27217) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
eventlist.0 | 2021-12-01 18:39:06.287 | error | (27217) Cannot read property 'replace' of undefined
eventlist.0 | 2021-12-01 18:39:06.286 | error | at /opt/iobroker/node_modules/iobroker.eventlist/main.js:621:21
eventlist.0 | 2021-12-01 18:39:06.286 | error | at new Promise (<anonymous>)
eventlist.0 | 2021-12-01 18:39:06.286 | error | at /opt/iobroker/node_modules/iobroker.eventlist/main.js:686:24
eventlist.0 | 2021-12-01 18:39:06.286 | error | at formatEvent (/opt/iobroker/node_modules/iobroker.eventlist/main.js:355:47)
eventlist.0 | 2021-12-01 18:39:06.286 | error | (27217) TypeError: Cannot read property 'replace' of undefined
eventlist.0 | 2021-12-01 18:39:06.286 | error | (27217) unhandled promise rejection: Cannot read property 'replace' of undefined
eventlist.0 | 2021-12-01 18:39:06.286 | error | (27217) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
eventlist.0 | 2021-12-01 18:38:32.283 | info | (27217) starting. Version 0.4.4 in /opt/iobroker/node_modules/iobroker.eventlist, node: v14.17.0, js-controller: 3.3.21


</body>
</html>`

**Comment by GermanBluefox** [comment]
Fixed in 0.5.0
